feat(nx): add the ability to filter truly affected by target(s)
lemonade-hq/traf pull request #23
Opened 2023-11-23 17:04 UTC by yharaskrik

When running the truly affected command you can now supply a `--target` option that will filter affected projects by what targets they have, for example when passing `--target build` only projects that have a `build` target will be returned.

2023-11-23 17:05 UTC, yharaskrik commented on tsconfig.base.json
> -      "@traf/turbo": ["libs/turbo/src/cli.ts"],
`nx format` did this?

2023-11-23 17:08 UTC, yharaskrik commented on libs/core/src/types.ts
> +  targets: string[];
Need to add this to the `turbo` `getTurboTrueAffectedProjects` return, not sure the structure of the project file though. Does turbo have a way to get the targets for a project?

2023-11-23 17:11 UTC, yharaskrik commented on libs/core/src/types.ts
> +  targets: string[];
Made it optional for the time being so we do not need to implement it for turbo right away unless its an easy fix, I just don't know much about turbo

2023-11-23 17:15 UTC, EladBezalel approved these changes

2023-11-23 17:16 UTC, EladBezalel requested changes
Seems to fail, look at the get affected step in setup, it returns an error (i need to fix that)

https://github.com/lemonade-hq/traf/actions/runs/6972639752/job/18975301951#step:6:1

2023-11-23 17:17 UTC, yharaskrik commented
> Seems to fail

Like when you actually run it? I added some tests to ensure its working right but maybe i need more tests. How did you test it locally so I can do the same?

2023-11-23 17:19 UTC, EladBezalel commented
Sorry, panic rejected (forgot that I control merges in open source 😅)
look here
https://github.com/lemonade-hq/traf/actions/runs/6972639752/job/18975301951#step:6:1

2023-11-23 17:22 UTC, yharaskrik commented
> Sorry, panic rejected (forgot that I control merges in open source 😅) look here https://github.com/lemonade-hq/traf/actions/runs/6972639752/job/18975301951#step:6:1

Ah gotcha I see! Hmm, I added to coerce to the args, but maybe that only coerces if there is a value? I probably need `default: []` for `--target` ya?

2023-11-23 17:26 UTC, EladBezalel commented
Yeah probably

2023-11-23 17:29 UTC, yharaskrik commented
> Yeah probably

Should be good now.

2023-11-23 17:39 UTC, EladBezalel commented
Tests are failing 😵‍💫

2023-11-23 17:40 UTC, ShayDavidson commented
Let's update the docs as well 🙏

2023-11-23 17:46 UTC, yharaskrik commented
> Let's update the docs as well 🙏

You got it, will do that when I have a second today

2023-11-24 00:03 UTC, EladBezalel approved these changes

2023-11-24 09:25 UTC, merged